### ISSUE TITLE
web interface issue

### ISSUE THREAD

**Issue by Mehran** [evilsocket/xray#31]
it seems every is okey but when i browse that ip address i see bad log and its empty . also i didn't have this issue on first Released .

```
____  ___
\   \/  /
 \     RAY v 1.0.0b
 /    by Simone 'evilsocket' Margaritelli
/___/\  \
      \_/

@ Saving session to mehran.co-xray-session.json
@ Web UI running on http://xxxxxxx:8080/

0.28 % completed, 35.80 req/s, 7 unique targets found so far ...
0.69 % completed, 44.50 req/s, 7 unique targets found so far ...
0.94 % completed, 40.63 req/s, 7 unique targets found so far ...
http: panic serving xxxxxxx:51691: [map]: [optional]: [xray.Target]: [optional]: [xray.Context]: [optional]: [xray.Machine]: unsupported type: chan interface {}
goroutine 3893 [running]:
net/http.(*conn).serve.func1(0xc420059300)
        /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xae96a0, 0xc42039f6f0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.JSON.Render(0xb0cb80, 0xc420330c00, 0x7f70d8237100, 0xc420405130, 0xc420405100, 0x7f70d8237100)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render/json.go:35 +0x96
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.(*JSON).Render(0xc4203ca4f0, 0x7f70d8237100, 0xc420405130, 0x7f70d8237100, 0xc420405130)
        <autogenerated>:10 +0x6f
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Render(0xc420405130, 0xc8, 0xf0b580, 0xc4203ca4f0)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:598 +0xb7
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).JSON(0xc420405130, 0xc8, 0xb0cb80, 0xc420330c00)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:629 +0x96
main.main.func1(0xc420405130)
        /root/work/src/github.com/evilsocket/xray/cmd/xray/main.go:154 +0x1fa
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc420405130)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:110 +0x5a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc420290360, 0xc420405130)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:337 +0x6bb
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc420290360, 0xf0ce80, 0xc4201aa1a0, 0xc42048e2d0)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:301 +0x130
net/http.serverHandler.ServeHTTP(0xc420238b80, 0xf0ce80, 0xc4201aa1a0, 0xc42048e2d0)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420059300, 0xf0dac0, 0xc420358640)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
http: panic serving xxxxx:51692: [map]: [optional]: [xray.Target]: [optional]: [xray.Context]: [optional]: [xray.Machine]: unsupported type: chan interface {}
goroutine 3894 [running]:
net/http.(*conn).serve.func1(0xc420059380)
        /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xae96a0, 0xc42055d420)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.JSON.Render(0xb0cb80, 0xc4205532f0, 0x7f70d8237100, 0xc4209fb6b0, 0xc4209fb600, 0x7f70d8237100)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render/json.go:35 +0x96
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.(*JSON).Render(0xc42055cb80, 0x7f70d8237100, 0xc4209fb6b0, 0x7f70d8237100, 0xc4209fb6b0)
        <autogenerated>:10 +0x6f
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Render(0xc4209fb6b0, 0xc8, 0xf0b580, 0xc42055cb80)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:598 +0xb7
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).JSON(0xc4209fb6b0, 0xc8, 0xb0cb80, 0xc4205532f0)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:629 +0x96
main.main.func1(0xc4209fb6b0)
        /root/work/src/github.com/evilsocket/xray/cmd/xray/main.go:154 +0x1fa
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4209fb6b0)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:110 +0x5a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc420290360, 0xc4209fb6b0)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:337 +0x6bb
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc420290360, 0xf0ce80, 0xc42024edd0, 0xc42048e870)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:301 +0x130
net/http.serverHandler.ServeHTTP(0xc420238b80, 0xf0ce80, 0xc42024edd0, 0xc42048e870)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420059380, 0xf0dac0, 0xc420358700)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
http: panic serving xxxxxxx:51690: [map]: [optional]: [xray.Target]: [optional]: [xray.Context]: [optional]: [xray.Machine]: unsupported type: chan interface {}
goroutine 3892 [running]:
net/http.(*conn).serve.func1(0xc420059280)
        /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xae96a0, 0xc42028c250)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.JSON.Render(0xb0cb80, 0xc4202888d0, 0x7f70d8237100, 0xc420280840, 0xc420280800, 0x7f70d8237100)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render/json.go:35 +0x96
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.(*JSON).Render(0xc4202fd960, 0x7f70d8237100, 0xc420280840, 0x7f70d8237100, 0xc420280840)
        <autogenerated>:10 +0x6f
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Render(0xc420280840, 0xc8, 0xf0b580, 0xc4202fd960)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:598 +0xb7
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).JSON(0xc420280840, 0xc8, 0xb0cb80, 0xc4202888d0)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:629 +0x96
main.main.func1(0xc420280840)
        /root/work/src/github.com/evilsocket/xray/cmd/xray/main.go:154 +0x1fa
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc420280840)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:110 +0x5a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc420290360, 0xc420280840)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:337 +0x6bb
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc420290360, 0xf0ce80, 0xc4201c7ee0, 0xc42048e0f0)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:301 +0x130
net/http.serverHandler.ServeHTTP(0xc420238b80, 0xf0ce80, 0xc4201c7ee0, 0xc42048e0f0)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420059280, 0xf0dac0, 0xc420358540)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
http: panic serving xxxxx:51689: [map]: [optional]: [xray.Target]: [optional]: [xray.Context]: [optional]: [xray.Machine]: unsupported type: chan interface {}
goroutine 3881 [running]:
net/http.(*conn).serve.func1(0xc420058700)
        /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xae96a0, 0xc42041e010)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.JSON.Render(0xb0cb80, 0xc420403800, 0x7f70d8237100, 0xc420281ad0, 0xc420281a00, 0x7f70d8237100)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render/json.go:35 +0x96
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.(*JSON).Render(0xc420429380, 0x7f70d8237100, 0xc420281ad0, 0x7f70d8237100, 0xc420281ad0)
        <autogenerated>:10 +0x6f
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Render(0xc420281ad0, 0xc8, 0xf0b580, 0xc420429380)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:598 +0xb7
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).JSON(0xc420281ad0, 0xc8, 0xb0cb80, 0xc420403800)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:629 +0x96
main.main.func1(0xc420281ad0)
        /root/work/src/github.com/evilsocket/xray/cmd/xray/main.go:154 +0x1fa
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc420281ad0)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:110 +0x5a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc420290360, 0xc420281ad0)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:337 +0x6bb
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc420290360, 0xf0ce80, 0xc4201bedd0, 0xc42048e960)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:301 +0x130
net/http.serverHandler.ServeHTTP(0xc420238b80, 0xf0ce80, 0xc4201bedd0, 0xc42048e960)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420058700, 0xf0dac0, 0xc4203f5b40)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
http: panic serving xxxxxxx:51693: [map]: [optional]: [xray.Target]: [optional]: [xray.Context]: [optional]: [xray.Machine]: unsupported type: chan interface {}
goroutine 3880 [running]:
net/http.(*conn).serve.func1(0xc420058680)
        /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xae96a0, 0xc420574140)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.JSON.Render(0xb0cb80, 0xc420380c00, 0x7f70d8237100, 0xc4200e84d0, 0xc4200e8400, 0x7f70d8237100)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render/json.go:35 +0x96
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.(*JSON).Render(0xc4203f75c0, 0x7f70d8237100, 0xc4200e84d0, 0x7f70d8237100, 0xc4200e84d0)
        <autogenerated>:10 +0x6f
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Render(0xc4200e84d0, 0xc8, 0xf0b580, 0xc4203f75c0)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:598 +0xb7
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).JSON(0xc4200e84d0, 0xc8, 0xb0cb80, 0xc420380c00)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:629 +0x96
main.main.func1(0xc4200e84d0)
        /root/work/src/github.com/evilsocket/xray/cmd/xray/main.go:154 +0x1fa
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4200e84d0)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:110 +0x5a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc420290360, 0xc4200e84d0)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:337 +0x6bb
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc420290360, 0xf0ce80, 0xc42005a4e0, 0xc42048e000)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:301 +0x130
net/http.serverHandler.ServeHTTP(0xc420238b80, 0xf0ce80, 0xc42005a4e0, 0xc42048e000)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420058680, 0xf0dac0, 0xc4203f5c40)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
http: panic serving xxxxx:51694: [map]: [optional]: [xray.Target]: [optional]: [xray.Context]: [optional]: [xray.Machine]: unsupported type: chan interface {}
goroutine 3895 [running]:
net/http.(*conn).serve.func1(0xc420059400)
        /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xae96a0, 0xc420478020)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.JSON.Render(0xb0cb80, 0xc420534ba0, 0x7f70d8237100, 0xc4209fa210, 0xc4209fa200, 0x7f70d8237100)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render/json.go:35 +0x96
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.(*JSON).Render(0xc42055d6c0, 0x7f70d8237100, 0xc4209fa210, 0x7f70d8237100, 0xc4209fa210)
        <autogenerated>:10 +0x6f
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Render(0xc4209fa210, 0xc8, 0xf0b580, 0xc42055d6c0)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:598 +0xb7
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).JSON(0xc4209fa210, 0xc8, 0xb0cb80, 0xc420534ba0)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:629 +0x96
main.main.func1(0xc4209fa210)
        /root/work/src/github.com/evilsocket/xray/cmd/xray/main.go:154 +0x1fa
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4209fa210)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:110 +0x5a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc420290360, 0xc4209fa210)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:337 +0x6bb
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc420290360, 0xf0ce80, 0xc42024e1a0, 0xc42048e1e0)
        /root/work/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:301 +0x130
net/http.serverHandler.ServeHTTP(0xc420238b80, 0xf0ce80, 0xc42024e1a0, 0xc42048e1e0)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420059400, 0xf0dac0, 0xc4203584c0)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
^C
```

**Comment by madaratech** [comment]
same here, before it was working well, after last update and build i see same issue while running the server, nothing shown running in UI, and these error on CLI.

**Comment by keleju** [comment]
Warning: You have 0 query credits.
@ Saving session to site-xray-session.json
@ Web UI running on http://0.0.0.0:8080/

0.02 % completed, 2.10 req/s, 3 unique targets found so far ...
0.05 % completed, 2.95 req/s, 5 unique targets found so far ...
0.07 % completed, 2.87 req/s, 6 unique targets found so far ...
0.09 % completed, 2.82 req/s, 8 unique targets found so far ...
0.11 % completed, 2.84 req/s, 8 unique targets found so far ...
0.13 % completed, 2.82 req/s, 11 unique targets found so far ...
0.16 % completed, 3.03 req/s, 11 unique targets found so far ...
http: panic serving x.x.x.x.x:36082: [map]: [optional]: [xray.Target]: [optional]: [xray.Context]: [optional]: [xray.Machine]: unsupported type: chan interface {}
goroutine 786 [running]:
net/http.(*conn).serve.func1(0xc4204f2460)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xb50580, 0xc4202dfb50)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.JSON.Render(0xb74e60, 0xc42039fc20, 0x7f8ec4b50e98, 0xc42026a4d0, 0xc42026a400, 0x7f8ec4b50e98)
	/go/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render/json.go:35 +0x80
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.(*JSON).Render(0xc4203af280, 0x7f8ec4b50e98, 0xc42026a4d0, 0x7f8ec4b50e98, 0xc42026a4d0)
	<autogenerated>:10 +0x6a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Render(0xc42026a4d0, 0xc8, 0xf6f920, 0xc4203af280)
	/go/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:598 +0x125


same issue

**Comment by Minitram** [comment]
I'm having the same issue here. The error messages are the same as @keleju reported (with `unsupported type: chan interface {}`). I noticed this one is missing in error mesages @Mehran pasted.  

Now, few more details that might help tracing the problem.
- Error messages appear only when browser connects to localhost:8080 and disappear immediately after the connection is closed (i.e. close the browser window / tab).
- If you don't use the browser and connect with curl instead, the error messages do not appear. However, curl only shows an empty template page with no values in progress bar etc.
- xray completes the job regardless of errors. The .json file is created correctly, and can be parsed using jq for example. It seems that only the http serving part is broken.

**Comment by xdavidhu** [comment]
Same here, it throws an error everytime the javascript trys to request the `http://127.0.0.1:8080/targets` page.

```http: panic serving 172.17.0.1:35270: [map]: [optional]: [xray.Target]: [optional]: [xray.Context]: [optional]: [xray.Machine]: unsupported type: chan interface {}
goroutine 2549 [running]:
net/http.(*conn).serve.func1(0xc420222aa0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xb50580, 0xc42030e9b0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.JSON.Render(0xb74e60, 0xc4203d5800, 0x7f992f78be10, 0xc42009da20, 0xc42009da00, 0x7f992f78be10)
	/go/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render/json.go:35 +0x80
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.(*JSON).Render(0xc42030e000, 0x7f992f78be10, 0xc42009da20, 0x7f992f78be10, 0xc42009da20)
	<autogenerated>:10 +0x6a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Render(0xc42009da20, 0xc8, 0xf6f920, 0xc42030e000)
	/go/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:598 +0x125
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).JSON(0xc42009da20, 0xc8, 0xb74e60, 0xc4203d5800)
	/go/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:629 +0x8d
main.main.func1(0xc42009da20)
	/go/src/github.com/evilsocket/xray/cmd/xray/main.go:154 +0x234
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42009da20)
	/go/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:110 +0x5a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc42023a120, 0xc42009da20)
	/go/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:337 +0x62a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc42023a120, 0xf71520, 0xc42017d960, 0xc4200d0600)
	/go/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:301 +0x16b
net/http.serverHandler.ServeHTTP(0xc42009cbb0, 0xf71520, 0xc42017d960, 0xc4200d0600)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420222aa0, 0xf72120, 0xc42036dbc0)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce```

**Comment by 0xroot** [comment]
The docker image seems to work well, however when I try to access the UI it doesn't get loaded. You can still grab the JSON file from the docker image with `docker exec`.

As for the CLI, it gives the errors mentioned previously.
